[package]
name = "verify"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"

[dev-dependencies]
stdsimd-test = { git = "https://github.com/rust-lang-nursery/stdsimd.git"  }
packed_simd = { path = "../.."  }
cfg-if = "^0.1"
interpolate_idents = "0.2"
