[package]
name = "verify"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]

[dev-dependencies]
stdsimd-test = { git = "https://github.com/rust-lang-nursery/stdsimd.git"  }
packed_simd = { path = "../.."  }