[package]
name = "triangle_xform"
version = "0.1.0"
authors = ["Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd = { path = "../.." }

[dev-dependencies]
rand = "0.5.5"
time = "0.1.40"
